import type { ExchangeLens, SearchFacetDefinition, SearchNavigationNode } from "./contracts";

const discoverChildren:SearchNavigationNode[]=[{id:"suggestions",label:"Suggestions",description:"Search records, organizations, geography, and lens concepts."},{id:"recent",label:"Recent searches",description:"Re-run or save searches you used recently."},{id:"saved",label:"Saved searches",description:"Run, rename, edit, alert on, or delete saved discovery criteria."}];
function geographyChildren(lens:ExchangeLens):SearchNavigationNode[]{const children:SearchNavigationNode[]=[{id:"exchange-geography",label:"Current Exchange geography",description:"Use the geography governing the Exchange view."},{id:"place",label:"Place / ZIP / locality",description:"Search a named geography."},{id:"radius",label:"Radius from map center",description:"Constrain located results by distance from the current map center."},{id:"viewport",label:"Current map area",description:"Use visible map bounds as query geography."}];if(lens==="resources"||lens==="capabilities")children.push({id:"service-area",label:"Service geography",description:"Find records whose service area covers the map center."});if(lens==="rfx")children.push({id:"performance-area",label:"Performance geography",description:"Find RFx whose performance area covers the map center."});return children;}
export function getSearchNavigationTree(lens:ExchangeLens):SearchNavigationNode{return{id:"root",label:"Universal Search",description:"Search the active Exchange lens without leaving the persistent shell.",children:[{id:"discover",label:"Discover",description:"Suggestions, recent searches, and saved searches.",children:discoverChildren},{id:"refine",label:"Refine results",description:"Shared filters, lens filters, geography, and sort.",children:[{id:"geography",label:"Geography & map",description:"Exchange geography, place, radius, viewport, and applicable service/performance areas.",children:geographyChildren(lens)},{id:"shared-filters",label:"Shared filters",description:"Map presence and organization ownership."},{id:"lens-filters",label:"Lens filters",description:"Domain-specific discovery criteria."},{id:"sort",label:"Sort",description:"Relevance, recency, title, or geography."}]}]};}
export const lensSearchFacetDefinitions:Record<ExchangeLens,SearchFacetDefinition[]>={
  rfx:[{key:"issuer",label:"Issuer",description:"Organization issuing the RFx."},{key:"procurementType",label:"Request type",description:"Solicitation/request type."},{key:"capability",label:"Capability",description:"Structured RFx requirement capability."},{key:"status",label:"Status",description:"RFx lifecycle status."}],
  resources:[{key:"provider",label:"Provider",description:"Organization offering the Resource."},{key:"category",label:"Category",description:"Resource/service category."},{key:"availability",label:"Availability",description:"Current availability."}],
  intelligence:[{key:"organization",label:"Organization",description:"Organization represented by the insight."},{key:"signal",label:"Signal",description:"Signal/observation type."},{key:"dataset",label:"Source",description:"Dataset or source context."}],
  capabilities:[{key:"organization",label:"Organization",description:"Organization whose capabilities are being discovered."},{key:"capability",label:"Capability",description:"Capability claim."},{key:"amacs",label:"AMACS",description:"Accepted AMACS mapping."},{key:"evidence",label:"Evidence",description:"Capability projection evidence state."}],
};
export function findSearchNavigationNode(root:SearchNavigationNode,id:string):SearchNavigationNode|undefined{if(root.id===id)return root;for(const child of root.children??[]){const match=findSearchNavigationNode(child,id);if(match)return match;}return undefined;}
