import type { ExchangeRecord } from "./contracts";

export const exchangeSeed: ExchangeRecord[] = [
  { id: "rfx-001", type: "rfx", title: "Regional Facilities Maintenance IDIQ", organization: "City of Chesapeake", summary: "Multi-trade maintenance and repair services across municipal facilities.", geography: "Chesapeake, VA", metadata: ["Sources Sought", "Due Sep 3", "$1M–$5M"], location: { lat: 36.77, lng: -76.29 }, saved: true },
  { id: "rfx-002", type: "rfx", title: "Cybersecurity Assessment Services", organization: "Harbor Systems Authority", summary: "Assessment, remediation planning, and continuous security advisory support.", geography: "Norfolk, VA", metadata: ["RFP", "Due Sep 12", "Professional Services"], location: { lat: 36.85, lng: -76.29 } },
  { id: "rfx-003", type: "rfx", title: "Small Business Supplier Outreach", organization: "Your Organization", summary: "Reference record proving own-organization action behavior.", geography: "Isle of Wight, VA", metadata: ["Draft", "Owned by you"], location: { lat: 36.9, lng: -76.71 }, ownedByViewer: true },
  { id: "res-001", type: "resource", title: "Mobile Training Classroom", organization: "Atlantic Skills Group", summary: "Twenty-four seat mobile classroom available for short-term deployment.", geography: "Suffolk, VA", metadata: ["Available", "Training", "Mobile asset"], location: { lat: 36.73, lng: -76.58 }, featured: true },
  { id: "res-002", type: "resource", title: "Proposal Review Capacity", organization: "Peninsula Advisory Partners", summary: "Experienced capture and proposal review support for government contractors.", geography: "Hampton Roads, VA", metadata: ["Services", "Remote", "Available now"] },
  { id: "res-003", type: "resource", title: "Conference Room Inventory", organization: "Your Organization", summary: "Reference resource owned by the signed-in organization.", geography: "Isle of Wight, VA", metadata: ["Owned by you", "Facilities"], location: { lat: 36.91, lng: -76.7 }, ownedByViewer: true },
  { id: "intel-001", type: "intelligence", title: "Maritime supplier concentration is rising", organization: "RFxchange Intelligence", summary: "Capability density increased around the Norfolk–Portsmouth corridor in the reference dataset.", geography: "Hampton Roads, VA", metadata: ["Market signal", "30-day view", "Maritime"], location: { lat: 36.84, lng: -76.32 } },
  { id: "intel-002", type: "intelligence", title: "Training demand exceeds visible local supply", organization: "RFxchange Intelligence", summary: "Reference insight demonstrating off-map intelligence in the drawer.", geography: "Virginia", metadata: ["Demand signal", "Workforce", "Off-map record"] },
  { id: "cap-001", type: "capability", title: "Industrial Electrical Installation", organization: "Tidewater Technical Services", summary: "Commercial and industrial electrical installation and maintenance capability.", geography: "Portsmouth, VA", metadata: ["AMACS mapped", "Electrical", "Field service"], location: { lat: 36.84, lng: -76.34 } },
  { id: "cap-002", type: "capability", title: "Business Intelligence & Market Analysis", organization: "Your Organization", summary: "Reference capability owned by the signed-in organization.", geography: "Isle of Wight, VA", metadata: ["AMACS mapped", "Owned by you"], location: { lat: 36.9, lng: -76.71 }, ownedByViewer: true },
  { id: "cap-003", type: "capability", title: "K-9 Training & Education", organization: "Regional Working Dog Institute", summary: "Training, curriculum, facility, and operational support capabilities.", geography: "Virginia", metadata: ["Training", "Education", "Off-map record"] },
];
