"use client";

import { useEffect, useMemo, useState } from "react";
import type { AmacsCandidateResponse, CapabilityCommand, CapabilityEvidenceKind, CapabilityOrganizationProfile, CapabilityRfxMatchResult } from "@/lib/capabilities/contracts";
import type { CapabilityWorkflowMode } from "@/lib/capabilities/actions";
import { capabilityNavigationById, type CapabilityNavigationNodeId } from "@/lib/capabilities/navigation";
import { withBasePath } from "@/lib/exchange/base-path";
import { CapabilityHierarchy } from "./capability-hierarchy";
import styles from "./capabilities.module.css";

type SavedRelationship = { id: string; recordId: string; recordTitle: string; recordOrganization: string; kind: string; lens: string; };
type ReferralRecord = { id: string; recordTitle: string; recipientOrganizationName: string; status: string; createdAt: string; };

async function postCapability(body: Record<string, unknown>) {
  const response = await fetch(withBasePath("/api/capabilities"), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Capability service failed"); return data;
}
async function postWorkflow(body: Record<string, unknown>) {
  const response = await fetch(withBasePath("/api/exchange/workflows"), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Shared workflow failed"); return data;
}
async function getWorkflowService(service: "saved" | "referrals") {
  const response = await fetch(withBasePath(`/api/exchange/workflows?service=${service}`), { cache: "no-store" });
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error ?? "Shared workflow service failed"); return data;
}

export function CapabilityWorkflowSurface({ profile, mode, onClose }: { profile: CapabilityOrganizationProfile; mode: CapabilityWorkflowMode; onClose: () => void }) {
  const [current, setCurrent] = useState(profile); const [activeNode, setActiveNode] = useState<CapabilityNavigationNodeId>(mode); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const [matches, setMatches] = useState<CapabilityRfxMatchResult[]>([]); const [amacs, setAmacs] = useState<AmacsCandidateResponse>(); const [savedRelationships, setSavedRelationships] = useState<SavedRelationship[]>([]); const [referrals, setReferrals] = useState<ReferralRecord[]>([]);
  const [selectedClaimId, setSelectedClaimId] = useState(profile.capabilities[0]?.id ?? ""); const [manualNode, setManualNode] = useState(""); const [manualLabel, setManualLabel] = useState(""); const [newName, setNewName] = useState(""); const [newDescription, setNewDescription] = useState("");
  const [evidenceKind, setEvidenceKind] = useState<CapabilityEvidenceKind>("document"); const [evidenceLabel, setEvidenceLabel] = useState(""); const [evidenceIssuer, setEvidenceIssuer] = useState(""); const [referralNote, setReferralNote] = useState(""); const [referralId, setReferralId] = useState<string>();
  const selectedClaim = current.capabilities.find((item) => item.id === selectedClaimId) ?? current.capabilities[0];
  const selectedOtherAvailable = !current.ownedByViewer;
  const node = capabilityNavigationById[activeNode];

  useEffect(() => { setCurrent(profile); }, [profile]);
  useEffect(() => {
    const url = new URL(window.location.href); url.searchParams.set("capNode", activeNode); window.history.replaceState(window.history.state, "", url);
    function sync() { const value = new URL(window.location.href).searchParams.get("capNode") as CapabilityNavigationNodeId | null; if (value && capabilityNavigationById[value]) setActiveNode(value); }
    window.addEventListener("popstate", sync); return () => window.removeEventListener("popstate", sync);
  }, []);
  useEffect(() => { if (activeNode === "match-rfx" && matches.length === 0) void loadMatches(); if (activeNode === "saved-organizations") void loadSaved(); if (activeNode === "cross-lens-referral") void loadReferrals(); }, [activeNode]);

  function setNode(next: CapabilityNavigationNodeId, mode: "push" | "replace" = "push") { setActiveNode(next); const url = new URL(window.location.href); url.searchParams.set("capNode", next); window.history[mode === "push" ? "pushState" : "replaceState"]({ ...window.history.state, capNode: next }, "", url); }
  function closeSurface() { const url = new URL(window.location.href); url.searchParams.delete("capNode"); window.history.replaceState(window.history.state, "", url); onClose(); }
  function openSharedDetail() { const url = new URL(window.location.href); url.pathname = withBasePath(`/exchange/capabilities/${current.exchangeRecordId}`); url.searchParams.delete("capNode"); window.history.pushState({}, "", url); onClose(); window.dispatchEvent(new PopStateEvent("popstate")); }
  function returnToBrowse(query?: string) { const url = new URL(window.location.href); url.pathname = withBasePath("/exchange/capabilities"); url.searchParams.delete("capNode"); if (query) url.searchParams.set("q", query); window.history.pushState({}, "", url); onClose(); window.dispatchEvent(new PopStateEvent("popstate")); }

  async function runCommand(command: CapabilityCommand, success: string) { setBusy(true); setMessage(undefined); try { const data = await postCapability({ operation: "command", recordId: current.exchangeRecordId, command }); setCurrent(data.profile); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : "Capability update failed"); } finally { setBusy(false); } }
  async function loadMatches() { setBusy(true); try { const data = await postCapability({ operation: "match", recordId: current.exchangeRecordId }); setMatches(data.matches ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "Match service failed"); } finally { setBusy(false); } }
  async function loadCandidates() { if (!selectedClaim) return; setBusy(true); try { const data = await postCapability({ operation: "amacs-candidates", recordId: current.exchangeRecordId, capabilityId: selectedClaim.id }); setAmacs(data); setMessage(data.reason); } catch (error) { setMessage(error instanceof Error ? error.message : "AMACS adapter failed"); } finally { setBusy(false); } }
  async function followOrganization() { setBusy(true); try { const data = await postWorkflow({ actionId: "follow", lens: "capabilities", recordId: current.exchangeRecordId, source: "detail" }); setCurrent((value) => ({ ...value, saved: Boolean(data.relationshipActive) })); setMessage(data.relationshipActive ? "Organization saved and followed." : "Organization removed from Saved & Watchlist."); setNode("saved-organizations"); } catch (error) { setMessage(error instanceof Error ? error.message : "Follow service failed"); } finally { setBusy(false); } }
  async function createReferral() { setBusy(true); try { const data = await postWorkflow({ actionId: "refer", lens: "capabilities", recordId: current.exchangeRecordId, source: "detail", payload: { note: referralNote } }); setReferralId(data.referral?.id); setMessage("Referral created in the shared workflow service."); } catch (error) { setMessage(error instanceof Error ? error.message : "Referral service failed"); } finally { setBusy(false); } }
  async function loadSaved() { try { const data = await getWorkflowService("saved"); setSavedRelationships(data.relationships ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "Saved service failed"); } }
  async function loadReferrals() { try { const data = await getWorkflowService("referrals"); setReferrals(data.referrals ?? []); } catch (error) { setMessage(error instanceof Error ? error.message : "Referral service failed"); } }

  function navigate(next: CapabilityNavigationNodeId) {
    if (next === "browse-organizations") { returnToBrowse(); return; }
    if (next === "current-profile" || next === "open-detail" || next === "capability-detail") { openSharedDetail(); return; }
    setNode(next);
  }

  const published = useMemo(() => current.capabilities.filter((item) => item.publicationStatus === "published"), [current]);
  let content: React.ReactNode;
  if (activeNode === "manage-capabilities") content = <><p className={styles.workflowIntro}>Maintain the active organization’s capability claims. Changes are persisted by the server-side Capabilities repository.</p><div className={styles.workflowGrid}>{current.capabilities.map((claim) => <div className={styles.panel} key={claim.id}><h3>{claim.name}</h3><p>{claim.description}</p><div className={styles.panelMeta}><span>{claim.mappingStatus}</span><span>{claim.publicationStatus}</span><span>{claim.evidence.length} evidence</span></div></div>)}</div><div className={styles.formPanel}><h3>Add capability</h3><label>Name<input value={newName} onChange={(e) => setNewName(e.target.value)} /></label><label>Description<textarea value={newDescription} onChange={(e) => setNewDescription(e.target.value)} /></label><button type="button" disabled={busy || !newName.trim() || !newDescription.trim()} onClick={() => void runCommand({ type: "add-claim", name: newName, description: newDescription }, "Capability added.")}>Add capability</button></div></>;
  else if (activeNode === "ai-amacs") content = <><p className={styles.workflowIntro}>AMACS candidates come from the configured governed release artifact. Candidate interpretation remains non-authoritative until the participant accepts, edits, or rejects it.</p><div className={styles.formPanel}><label>Capability<select value={selectedClaimId} onChange={(e) => { setSelectedClaimId(e.target.value); setAmacs(undefined); }}>{current.capabilities.map((claim) => <option key={claim.id} value={claim.id}>{claim.name}</option>)}</select></label><button type="button" disabled={busy || !selectedClaim} onClick={() => void loadCandidates()}>Get AMACS candidates</button>{amacs?.candidates.map((candidate) => <button className={styles.candidate} type="button" key={candidate.conceptId} onClick={() => void runCommand({ type: "set-amacs-mapping", capabilityId: selectedClaim!.id, disposition: "accept", amacsNodeId: candidate.conceptId, amacsLabel: candidate.label }, `Accepted ${candidate.label}.`)}><strong>{candidate.label}</strong><small>{candidate.conceptId} · {Math.round(candidate.score * 100)}% lexical fit</small></button>)}<h3>Manual mapping</h3><label>AMACS concept ID<input value={manualNode} onChange={(e) => setManualNode(e.target.value)} /></label><label>AMACS label<input value={manualLabel} onChange={(e) => setManualLabel(e.target.value)} /></label><div className={styles.buttonRow}><button type="button" disabled={!selectedClaim || !manualNode.trim() || !manualLabel.trim()} onClick={() => void runCommand({ type: "set-amacs-mapping", capabilityId: selectedClaim!.id, disposition: "edit", amacsNodeId: manualNode, amacsLabel: manualLabel }, "AMACS mapping saved.")}>Save mapping</button><button type="button" disabled={!selectedClaim} onClick={() => void runCommand({ type: "set-amacs-mapping", capabilityId: selectedClaim!.id, disposition: "reject" }, "Mapping rejected; manual review remains open.")}>Reject</button></div></div></>;
  else if (activeNode === "capability-evidence") content = <><p className={styles.workflowIntro}>Evidence is stored with the claim as provenance-bearing metadata. It supports a claim without automatically independently verifying it.</p><div className={styles.formPanel}><label>Capability<select value={selectedClaimId} onChange={(e) => setSelectedClaimId(e.target.value)}>{current.capabilities.map((claim) => <option key={claim.id} value={claim.id}>{claim.name}</option>)}</select></label><label>Evidence type<select value={evidenceKind} onChange={(e) => setEvidenceKind(e.target.value as CapabilityEvidenceKind)}><option value="certification">Certification</option><option value="license">License</option><option value="past-performance">Past performance</option><option value="case-study">Case study</option><option value="document">Document</option><option value="link">Link</option></select></label><label>Label<input value={evidenceLabel} onChange={(e) => setEvidenceLabel(e.target.value)} /></label><label>Issuer / source<input value={evidenceIssuer} onChange={(e) => setEvidenceIssuer(e.target.value)} /></label><button type="button" disabled={busy || !selectedClaim || !evidenceLabel.trim()} onClick={() => void runCommand({ type: "add-evidence", capabilityId: selectedClaim!.id, kind: evidenceKind, label: evidenceLabel, issuer: evidenceIssuer || undefined }, "Evidence added.")}>Add evidence</button></div>{selectedClaim?.evidence.map((item) => <div className={styles.panel} key={item.id}><h3>{item.label}</h3><p>{item.kind}{item.issuer ? ` · ${item.issuer}` : ""}</p><button type="button" onClick={() => void runCommand({ type: "remove-evidence", capabilityId: selectedClaim.id, evidenceId: item.id }, "Evidence removed.")}>Remove</button></div>)}</>;
  else if (activeNode === "capability-gaps") content = <><p className={styles.workflowIntro}>Gaps are recalculated from the persisted profile after every capability mutation.</p><div className={styles.workflowGrid}>{current.gaps.length ? current.gaps.map((gap) => <div className={styles.panel} key={gap.id}><h3>{gap.label}</h3><p>{gap.reason}</p><button type="button" onClick={() => returnToBrowse(gap.suggestedSearch)}>Search organizations for this gap</button></div>) : <div className={styles.panel}><h3>No profile gaps</h3><p>The current profile has no mapping, evidence, or publication gaps.</p></div>}</div></>;
  else if (activeNode === "save-publish") content = <><p className={styles.workflowIntro}>Save persists the current state. Publish makes participant-confirmed AMACS claims visible in the Exchange and leaves unresolved mappings in Ready state.</p><div className={styles.buttonRow}><button type="button" disabled={busy} onClick={() => void runCommand({ type: "save-profile" }, "Capability profile saved.")}>Save updates</button><button type="button" disabled={busy} onClick={() => void runCommand({ type: "publish-profile" }, "Eligible claims published to the Exchange.")}>Publish updates</button><button type="button" onClick={() => setNode("exchange-available")}>Review Exchange availability</button></div></>;
  else if (activeNode === "exchange-available") content = <><p className={styles.workflowIntro}>This is the source-defined terminal state for the own-organization path.</p><div className={styles.panel}><h3>{current.organizationName}</h3><p>{published.length} of {current.capabilities.length} capability claims are published and available to the Exchange projection.</p><div className={styles.panelMeta}>{published.map((item) => <span key={item.id}>{item.name}</span>)}</div></div><button type="button" onClick={closeSurface}>Return to Capabilities lens</button></>;
  else if (activeNode === "view-capabilities") content = <><p className={styles.workflowIntro}>Review the selected organization’s capability profile before matching or choosing a next action.</p><div className={styles.workflowGrid}>{current.capabilities.map((claim) => <div className={styles.panel} key={claim.id}><h3>{claim.name}</h3><p>{claim.description}</p><div className={styles.panelMeta}><span>{claim.mappingStatus}</span><span>{claim.evidence.length} evidence</span></div></div>)}</div><button type="button" onClick={() => setNode("match-rfx")}>Match to RFx / requirement</button></>;
  else if (activeNode === "match-rfx") content = <><p className={styles.workflowIntro}>Matches are computed from the structured RFx requirements in TestRFx. Eligibility and documentation are left uncertain instead of being inferred from capabilities.</p><div className={styles.workflowGrid}>{matches.map((match) => <div className={styles.panel} key={match.id}><h3>{match.title}</h3><p>{match.issuer} · {match.summary}</p>{match.requirements.map((req) => <div className={styles.requirement} key={req.requirementId}><strong>{req.label}</strong><span>{req.state}</span><small>{req.reason}</small></div>)}</div>)}</div><button type="button" onClick={() => setNode("decide-next-action")}>Decide next action</button></>;
  else if (activeNode === "decide-next-action") content = <><p className={styles.workflowIntro}>The source defines exactly three next-action branches.</p><div className={styles.decisionGrid}><button type="button" onClick={() => setNode("refer")}>Refer<span>Cross-lens referral workflow</span></button><button type="button" onClick={() => setNode("save-follow")}>Save / Follow<span>Watchlist / saved organizations</span></button><button type="button" onClick={() => setNode("open-detail")}>Open detail<span>Capability detail / supporting evidence</span></button></div></>;
  else if (activeNode === "refer") content = <><p className={styles.workflowIntro}>Create a referral through the shared workflow service, anchored to this organization capability profile.</p><div className={styles.formPanel}><label>Referral note<textarea value={referralNote} onChange={(e) => setReferralNote(e.target.value)} /></label><button type="button" disabled={busy} onClick={() => void createReferral()}>Create referral</button>{referralId ? <button type="button" onClick={() => setNode("cross-lens-referral")}>Continue referral workflow</button> : null}</div></>;
  else if (activeNode === "cross-lens-referral") content = <><p className={styles.workflowIntro}>Cross-lens referrals are stored by the shared workflow repository.</p><div className={styles.workflowGrid}>{referrals.length ? referrals.map((item) => <div className={styles.panel} key={item.id}><h3>{item.recipientOrganizationName}</h3><p>{item.recordTitle} · {item.status}</p><small>{item.id}</small></div>) : <div className={styles.panel}><h3>No referrals yet</h3><p>Create the referral from the previous step.</p></div>}</div></>;
  else if (activeNode === "save-follow") content = <><p className={styles.workflowIntro}>Persist this organization in the shared Saved & Watchlist relationship service.</p><button type="button" disabled={busy} onClick={() => void followOrganization()}>{current.saved ? "Remove from Saved / Follow" : "Save / Follow organization"}</button></>;
  else if (activeNode === "saved-organizations") content = <><p className={styles.workflowIntro}>This is the shared Watchlist / saved-organizations service projection.</p><div className={styles.workflowGrid}>{savedRelationships.length ? savedRelationships.map((item) => <div className={styles.panel} key={item.id}><h3>{item.recordOrganization}</h3><p>{item.recordTitle} · {item.kind} · {item.lens}</p></div>) : <div className={styles.panel}><h3>No saved relationships</h3><p>Use Save / Follow to add an organization.</p></div>}</div></>;
  else if (activeNode === "open-detail" || activeNode === "capability-detail" || activeNode === "current-profile") content = <><p className={styles.workflowIntro}>Open the shared detail controller while preserving the Capabilities lens and selected record.</p><button type="button" onClick={openSharedDetail}>Open capability detail / supporting evidence</button></>;
  else if (activeNode === "browse-organizations") content = <><p className={styles.workflowIntro}>Browse and search remain owned by the persistent Exchange search, map, and drawer.</p><button type="button" onClick={() => returnToBrowse()}>Return to organization results</button></>;
  else content = <><p className={styles.workflowIntro}>{node?.description}</p><button type="button" onClick={() => returnToBrowse()}>Return to Capabilities lens</button></>;

  return <section className={styles.workflowSurface} role="dialog" aria-modal="true" aria-label="Capabilities workflow"><header><button type="button" onClick={closeSurface}>← Back</button><div><small>Capabilities workflow</small><h2>{node?.label ?? activeNode}</h2></div><button type="button" onClick={closeSurface} aria-label="Close">×</button></header><div className={styles.workflowBody}><CapabilityHierarchy activeNodeId={activeNode} selectedOtherAvailable={selectedOtherAvailable} onNavigate={navigate} />{content}{message ? <p className={styles.serviceMessage} role="status">{message}</p> : null}</div></section>;
}
