export const organizationTypes = ["Business","Supplier","Buyer / Issuer","Government","Economic Development Organization","Resource Provider","Chamber / Association","Lender / Capital Provider","University / Education","Nonprofit","Other"] as const;
export type OrganizationType = (typeof organizationTypes)[number];
export type OrganizationClaimState = "unclaimed" | "claimed" | "verified";
export type OrganizationResolutionMode = "claim" | "join" | "create";
export interface OrganizationCandidate { id: string; name: string; aliases: string[]; type: OrganizationType; website?: string; domain?: string; locality?: string; region?: string; claimState: OrganizationClaimState; }
export interface OrganizationSearchInput { query?: string; domain?: string; }
export interface OrganizationResolution { mode: OrganizationResolutionMode; organizationId: string; organizationName: string; organizationType: OrganizationType; website?: string; membershipState: "active" | "pending-approval" | "authority-pending"; authorityState: "invited" | "self-attested" | "pending"; nextPath: "/onboarding/geography"; referenceOnly: true; }
const organizationSeed: OrganizationCandidate[] = [
{id:"org-city-chesapeake",name:"City of Chesapeake",aliases:["Chesapeake","City of Chesapeake Virginia"],type:"Government",website:"https://www.cityofchesapeake.net",domain:"cityofchesapeake.net",locality:"Chesapeake",region:"Virginia",claimState:"verified"},
{id:"org-harbor-systems-authority",name:"Harbor Systems Authority",aliases:["Harbor Systems"],type:"Buyer / Issuer",website:"https://harborsystems.example",domain:"harborsystems.example",locality:"Norfolk",region:"Virginia",claimState:"claimed"},
{id:"org-atlantic-skills-group",name:"Atlantic Skills Group",aliases:["Atlantic Skills"],type:"Resource Provider",website:"https://atlanticskills.example",domain:"atlanticskills.example",locality:"Suffolk",region:"Virginia",claimState:"unclaimed"},
{id:"org-peninsula-advisory-partners",name:"Peninsula Advisory Partners",aliases:["Peninsula Advisory"],type:"Supplier",website:"https://peninsulaadvisory.example",domain:"peninsulaadvisory.example",locality:"Hampton Roads",region:"Virginia",claimState:"claimed"},
{id:"org-tidewater-technical-services",name:"Tidewater Technical Services",aliases:["Tidewater Technical","TTS"],type:"Business",website:"https://tidewatertechnical.example",domain:"tidewatertechnical.example",locality:"Portsmouth",region:"Virginia",claimState:"verified"},
{id:"org-regional-working-dog-institute",name:"Regional Working Dog Institute",aliases:["Working Dog Institute","RWDI"],type:"University / Education",website:"https://workingdoginstitute.example",domain:"workingdoginstitute.example",region:"Virginia",claimState:"unclaimed"},
];
export function normalizeOrganizationTerm(value = "") { return value.toLowerCase().replace(/\b(the|llc|l\.l\.c|inc|incorporated|corp|corporation|company|co)\b/g," ").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," "); }
export function normalizeDomain(value = "") { return value.trim().toLowerCase().replace(/^https?:\/\//,"").replace(/^www\./,"").split("/")[0]; }
function scoreCandidate(candidate: OrganizationCandidate,input: OrganizationSearchInput) { const query=normalizeOrganizationTerm(input.query); const domain=normalizeDomain(input.domain); const name=normalizeOrganizationTerm(candidate.name); const aliases=candidate.aliases.map(normalizeOrganizationTerm); let score=0; if(domain&&candidate.domain===domain)score+=12; if(query&&name===query)score+=10; if(query&&aliases.includes(query))score+=9; if(query&&name.includes(query))score+=6; if(query&&aliases.some((alias)=>alias.includes(query)))score+=5; if(query){const terms=query.split(" ").filter(Boolean); const haystack=[name,...aliases].join(" "); score+=terms.filter((term)=>haystack.includes(term)).length;} return score; }
export function searchOrganizations(input: OrganizationSearchInput) { const hasInput=Boolean(normalizeOrganizationTerm(input.query)||normalizeDomain(input.domain)); if(!hasInput)return organizationSeed.slice(0,4); return organizationSeed.map((candidate)=>({candidate,score:scoreCandidate(candidate,input)})).filter(({score})=>score>0).sort((a,b)=>b.score-a.score).map(({candidate})=>candidate); }
export function resolutionModeFor(candidate: OrganizationCandidate): OrganizationResolutionMode { return candidate.claimState==="unclaimed"?"claim":"join"; }
export function createReferenceResolution(input:{mode:OrganizationResolutionMode;candidate?:OrganizationCandidate;name?:string;type?:OrganizationType;website?:string;}):OrganizationResolution { if(input.candidate){const mode=resolutionModeFor(input.candidate);return{mode,organizationId:input.candidate.id,organizationName:input.candidate.name,organizationType:input.candidate.type,website:input.candidate.website,membershipState:mode==="claim"?"authority-pending":"pending-approval",authorityState:"pending",nextPath:"/onboarding/geography",referenceOnly:true};} const name=input.name?.trim(); if(!name||!input.type)throw new Error("Organization name and type are required."); return{mode:"create",organizationId:`reference-${normalizeOrganizationTerm(name).replace(/\s+/g,"-")||"organization"}`,organizationName:name,organizationType:input.type,website:input.website?.trim()||undefined,membershipState:"active",authorityState:"self-attested",nextPath:"/onboarding/geography",referenceOnly:true}; }
