import type { CapabilityOrganizationProfile } from "./contracts";
import { capabilityProfileToExchangeRecord } from "./contracts";

export const capabilityProfiles: CapabilityOrganizationProfile[] = [
  {
    exchangeRecordId: "cap-001",
    organizationName: "Tidewater Technical Services",
    summary: "Industrial electrical installation, preventive maintenance, and field-service capacity for commercial and public-sector facilities.",
    geography: "Portsmouth, VA",
    serviceAreas: ["Portsmouth", "Norfolk", "Chesapeake", "Hampton Roads"],
    keywords: ["industrial electrical", "field service", "preventive maintenance", "facilities"],
    profileStrength: 88,
    location: { lat: 36.84, lng: -76.34 },
    cardMedia: {
      kind: "image",
      label: "Electrical capability",
      src: "/exchange-media/capability-electrical.svg",
      alt: "Illustrated electrical system preview for the TestRFx capability reference",
    },
    capabilities: [
      {
        id: "industrial-electrical",
        name: "Industrial Electrical Installation",
        description: "Install, modify, and maintain commercial and industrial electrical systems in occupied and active facilities.",
        amacsNodeId: "amacs.reference.industrial-electrical-installation",
        amacsLabel: "AMACS reference projection · Industrial Electrical Installation",
        mappingStatus: "accepted",
        publicationStatus: "published",
        evidenceState: "supported",
        specialties: ["installation", "retrofit", "electrical distribution"],
        evidence: [
          { id: "cap-001-ev-1", kind: "license", label: "Virginia electrical contractor license", issuer: "Reference credential" },
          { id: "cap-001-ev-2", kind: "past-performance", label: "Municipal facilities electrical modernization", note: "Reference past-performance artifact" },
        ],
      },
      {
        id: "preventive-maintenance",
        name: "Electrical Preventive Maintenance",
        description: "Inspection, preventive maintenance, troubleshooting, and corrective field service for facility electrical systems.",
        amacsNodeId: "amacs.reference.electrical-maintenance",
        amacsLabel: "AMACS reference projection · Electrical Maintenance",
        mappingStatus: "accepted",
        publicationStatus: "published",
        evidenceState: "supported",
        specialties: ["inspection", "troubleshooting", "maintenance"],
        evidence: [{ id: "cap-001-ev-3", kind: "case-study", label: "Multi-site preventive maintenance program" }],
      },
    ],
    gaps: [
      { id: "cap-001-gap-1", label: "Building controls integration", reason: "A representative facilities requirement includes controls integration that is not present in the published profile.", suggestedSearch: "building controls integration" },
    ],
    rfxMatches: [
      { id: "rfx-001", title: "Regional Facilities Maintenance IDIQ", issuer: "City of Chesapeake", coverage: "strong", summary: "Electrical installation and preventive maintenance align with two core work categories; controls integration remains a partner gap." },
    ],
  },
  {
    exchangeRecordId: "cap-002",
    organizationName: "Your Organization",
    summary: "Business intelligence, market analysis, site-selection, and operating-process capabilities represented as the signed-in organization reference profile.",
    geography: "Isle of Wight, VA",
    serviceAreas: ["Isle of Wight", "Hampton Roads", "Virginia"],
    keywords: ["business intelligence", "market analysis", "site selection", "CRM", "process design"],
    profileStrength: 82,
    location: { lat: 36.9, lng: -76.71 },
    ownedByViewer: true,
    saved: true,
    capabilities: [
      {
        id: "business-intelligence",
        name: "Business Intelligence & Market Analysis",
        description: "Translate market, customer, operational, and competitive data into decision-ready analysis and recommendations.",
        amacsNodeId: "amacs.reference.business-intelligence-market-analysis",
        amacsLabel: "AMACS reference projection · Business Intelligence & Market Analysis",
        mappingStatus: "accepted",
        publicationStatus: "published",
        evidenceState: "supported",
        specialties: ["market sizing", "competitive analysis", "decision support"],
        evidence: [
          { id: "cap-002-ev-1", kind: "case-study", label: "Regional market-analysis engagement" },
          { id: "cap-002-ev-2", kind: "document", label: "Reference methodology summary" },
        ],
      },
      {
        id: "site-selection",
        name: "Site Selection & Location Analysis",
        description: "Evaluate locations using workforce, infrastructure, market, cost, and operating requirements.",
        amacsNodeId: "amacs.reference.site-selection",
        amacsLabel: "AMACS reference projection · Site Selection & Location Analysis",
        mappingStatus: "accepted",
        publicationStatus: "published",
        evidenceState: "supported",
        specialties: ["location strategy", "workforce analysis", "geographic comparison"],
        evidence: [{ id: "cap-002-ev-3", kind: "past-performance", label: "Multi-location site evaluation" }],
      },
      {
        id: "crm-process",
        name: "CRM & Operating Process Design",
        description: "Design practical customer, pipeline, reporting, and management workflows that connect people, data, and execution.",
        amacsNodeId: "amacs.reference.crm-operating-process-design",
        amacsLabel: "AMACS reference projection · CRM & Operating Process Design",
        mappingStatus: "needs-review",
        publicationStatus: "ready",
        evidenceState: "claimed",
        specialties: ["CRM", "pipeline design", "workflow design"],
        evidence: [],
      },
    ],
    gaps: [
      { id: "cap-002-gap-1", label: "CRM capability evidence", reason: "The capability is ready to publish but does not yet have supporting evidence attached.", suggestedSearch: "CRM operating process evidence" },
      { id: "cap-002-gap-2", label: "Cybersecurity assessment partner", reason: "A representative RFx match contains a cybersecurity requirement outside the current published capability set.", suggestedSearch: "cybersecurity assessment" },
    ],
    rfxMatches: [
      { id: "rfx-002", title: "Cybersecurity Assessment Services", issuer: "Harbor Systems Authority", coverage: "partial", summary: "Market analysis and operating-process work can support discovery and remediation planning, but cybersecurity assessment remains a capability gap." },
    ],
  },
  {
    exchangeRecordId: "cap-003",
    organizationName: "Regional Working Dog Institute",
    summary: "K-9 training, curriculum development, and facility operations capability for working-dog programs and handlers.",
    geography: "Virginia",
    serviceAreas: ["Virginia", "Mid-Atlantic"],
    keywords: ["K-9", "working dog", "handler training", "curriculum", "kennel operations"],
    profileStrength: 74,
    organizationMedia: {
      logo: {
        kind: "logo",
        label: "Organization mark",
        src: "/exchange-media/organization-rwdi-mark.svg",
        alt: "Reference organization mark for Regional Working Dog Institute",
      },
    },
    capabilities: [
      {
        id: "k9-training",
        name: "K-9 Training & Education",
        description: "Deliver structured working-dog and handler training programs across operational and educational contexts.",
        amacsNodeId: "amacs.reference.k9-training-education",
        amacsLabel: "AMACS reference projection · K-9 Training & Education",
        mappingStatus: "accepted",
        publicationStatus: "published",
        evidenceState: "supported",
        specialties: ["handler education", "working dog training", "program delivery"],
        evidence: [{ id: "cap-003-ev-1", kind: "case-study", label: "Working-dog training cohort" }],
      },
      {
        id: "curriculum-development",
        name: "Training Curriculum Development",
        description: "Design competency-based course structure, instructional materials, and practical assessment pathways.",
        amacsNodeId: "amacs.reference.training-curriculum-development",
        amacsLabel: "AMACS reference projection · Training Curriculum Development",
        mappingStatus: "suggested",
        publicationStatus: "ready",
        evidenceState: "claimed",
        specialties: ["curriculum", "instructional design", "assessment"],
        evidence: [],
      },
    ],
    gaps: [
      { id: "cap-003-gap-1", label: "Curriculum evidence", reason: "The curriculum-development mapping is suggested and does not yet have a supporting artifact.", suggestedSearch: "training curriculum evidence" },
    ],
    rfxMatches: [],
  },
  {
    exchangeRecordId: "cap-004",
    organizationName: "BlueLine Construction",
    summary: "General contracting, design-build coordination, and commercial renovation capability with regional project delivery coverage.",
    geography: "Suffolk, VA",
    serviceAreas: ["Suffolk", "Isle of Wight", "Chesapeake", "Hampton Roads"],
    keywords: ["general contractor", "design-build", "commercial renovation", "construction management"],
    profileStrength: 91,
    location: { lat: 36.73, lng: -76.58 },
    featured: true,
    capabilities: [
      {
        id: "general-contracting",
        name: "General Contracting",
        description: "Coordinate subcontractors, schedules, quality, safety, and field execution for commercial construction projects.",
        amacsNodeId: "amacs.reference.general-contracting",
        amacsLabel: "AMACS reference projection · General Contracting",
        mappingStatus: "accepted",
        publicationStatus: "published",
        evidenceState: "supported",
        specialties: ["commercial construction", "subcontractor coordination", "field execution"],
        evidence: [
          { id: "cap-004-ev-1", kind: "license", label: "Virginia contractor license", issuer: "Reference credential" },
          { id: "cap-004-ev-2", kind: "past-performance", label: "Occupied-facility renovation project" },
        ],
      },
      {
        id: "design-build",
        name: "Design-Build Coordination",
        description: "Coordinate design, estimating, procurement, and construction execution through an integrated delivery approach.",
        amacsNodeId: "amacs.reference.design-build-coordination",
        amacsLabel: "AMACS reference projection · Design-Build Coordination",
        mappingStatus: "accepted",
        publicationStatus: "published",
        evidenceState: "supported",
        specialties: ["design-build", "preconstruction", "delivery coordination"],
        evidence: [{ id: "cap-004-ev-3", kind: "case-study", label: "Design-build tenant improvement" }],
      },
      {
        id: "commercial-renovation",
        name: "Commercial Renovation",
        description: "Plan and execute phased renovation work while maintaining operating continuity and stakeholder coordination.",
        amacsNodeId: "amacs.reference.commercial-renovation",
        amacsLabel: "AMACS reference projection · Commercial Renovation",
        mappingStatus: "accepted",
        publicationStatus: "published",
        evidenceState: "supported",
        specialties: ["renovation", "occupied facilities", "phased construction"],
        evidence: [{ id: "cap-004-ev-4", kind: "past-performance", label: "Phased commercial renovation" }],
      },
    ],
    gaps: [
      { id: "cap-004-gap-1", label: "Specialty electrical self-performance", reason: "The representative facilities RFx includes electrical work that would likely require a specialty partner.", suggestedSearch: "industrial electrical installation" },
    ],
    rfxMatches: [
      { id: "rfx-001", title: "Regional Facilities Maintenance IDIQ", issuer: "City of Chesapeake", coverage: "strong", summary: "General contracting and occupied-facility renovation align strongly; specialty electrical work is a teaming gap." },
    ],
  },
];

export const capabilityExchangeRecords = capabilityProfiles.map(capabilityProfileToExchangeRecord);

export function getCapabilityProfileByExchangeRecordId(recordId: string) {
  return capabilityProfiles.find((profile) => profile.exchangeRecordId === recordId);
}
